language: java

branches:
  except:
    - /^feature.*$/

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "pdACrnUpOihPQH/Vn5peJfkt+bRlhsp++NP9e/F6KBpMptvlmr3B+DD45RjFQktiyDIK8OrsAQ35QwpuoZDx/NMRaeXfhVq2QA87E56YwezsKyE3FMlNGPC8PwoEtnBieAAEWNnhiaQa0xPRXPLS/fwbqD8w7BJtxAGjsaoOzac="

before_install:
  - sudo rm -r /usr/local/gradle
  - curl -LO http://services.gradle.org/distributions/gradle-2.3-bin.zip
  - unzip -q gradle-2.3-bin.zip
  - sudo mv gradle-2.3 /usr/local/gradle

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

after_failure: 
  - cat /home/travis/build/gatzka/java-scan/cov-int/build-log.txt
	  
#after_success: 
#  - cat /home/travis/build/gatzka/java-scan/cov-int/build-log.txt

addons:
  coverity_scan:
    project:
      name: "gatzka/java-scan"
      description: "Build submitted via Travis CI"
    notification_email: stephan.gatzka@gmail.com
    build_command: "/usr/local/gradle/bin/gradle clean assemble"
    branch_pattern: coverity_scan
