language: java

branches:
  except:
    - /^feature.*$/

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
  - secure: "txucPw09tA8laIbppuF8q63G7E88fandOSsAZrsEWhSA4HpzP+FizIKsiokmJr/uA5zDitWMSkKTHYbz/wK8zgt0Hyb5w+krXG0gXSqJolMdOPE2/tm4pS0tAwbJFMxHCtxfvMeA97LIWvwUAcQ336BKWdoT+xeawGBSh/EsGpM="

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

after_script: 
  - cat /home/travis/build/HBM/java-scan/cov-int/build-log.txt

addons:
  coverity_scan:
    project:
      name: "HBM/java-scan"
      description: "Build submitted via Travis CI"
    build_script_url: https://raw.githubusercontent.com/HBM/java-scan/coverity_scan/scripts/travis/travisci_build_coverity_scan.sh
    notification_email: stephan.gatzka@hbm.com
    build_command: "mvn compile"
    branch_pattern: coverity_scan
